services:
  homon:
    image: ghcr.io/heckelmann/homon:main
    container_name: homon
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/homon.db
      - NODE_ENV=production
      - APP_URL=http://localhost:3000
      - ENCRYPTION_KEY=your_encryption_key_here
    restart: unless-stopped
